language: elixir

elixir:
  - 1.10
  - 1.9
  - 1.8

otp_release:
  - '22.3'
  - '23.0.2'

before_script:
  - mix compile –warnings-as-errors
  - mix credo --strict
  - if [[ "$TRAVIS_ELIXIR_VERSION" =~ "1.10" ]]; then mix format mix.exs "{config,lib,test}/**/*.{ex,exs}" --check-formatted; fi

before_install:
  - sudo apt-get install -y build-essential erlang-dev libmagic-dev
